setfilter :bear:

diff --git a/setfilter b/setfilter
--- a/setfilter
+++ b/setfilter
@@ -46,7 +46,6 @@ else
   done
   echo " -- $file exists and can be executed"
 fi
-
 echo " - checking supplied filter"
 for i in $filters; do
   if [ $i == $1 ]; then
@@ -54,13 +53,11 @@ for i in $filters; do
     break
   fi
 done
-
 [ -z $filter ] && echo " -- $1 is not a valid --compiler-filter" && exit 2
-
 echo " -- $filter is a valid --compiler-filter"
-
 echo " --- setting $filter for $file"
-sed -i "s/filter=.*/filter=${filter}/g" $file
+sed -i "s/filter=.*/filter=${filter}/g" $file 2>/dev/null
+[ $? -ne 0 ] && echo " - failed" && exit 6
 grep -q "filter=${filter}" $file && { 
   echo " - successfully changed to $filter"
   echo " - reboot and wipe dalvik-cache for changes to apply"
